config/routes.rb
# -*- coding: utf-8 -*-
RadiheyRails::Application.routes.draw do
  root to: 'top#show'

  match '/activate/:pre_register_token', to: 'users#activate', :as => :activate
  match 'activated', to: 'users#activated', :as => :activated
  match 'join', to: 'users#new', :as => :join
  match 'login', to: 'user_sessions#new', :as => :login
  match 'logout', to: 'user_sessions#destroy', :as => :logout

  #match 'account_settings', to: 'users#edit', :as => :account_settings

  resources :user_sessions

  resources :users do
    get :pre_registered
  end

  scope 'settings' do
    resources :button_images
    resources :default_button_sets do
      get :add_button, :on => :collection
      post :upload, :on => :collection
    end

    match 'account', to: 'users#edit', :as => :account_settings
    resources :buttons
    resources :button_ses do
      get 'list_all', :as => :list_all, :on => :collection
    end
    resources :channels do
      get "buttons/:set_id", action: "buttons", :on => :member, :as => :buttons
      get "selected_buttons/:set_id", action: "selected_buttons", :on => :member, :as => :selected_buttons
      get 'get_buttons/:persona_id', to: 'channels#get_buttons_by_persona', :as => :get_buttons_by_persona
    end
  end

  scope ":username" do
    scope ':channel_id' do
      match 'get_buttons/:persona_id', to: 'channels#get_selected_buttons_by_persona', :as => :get_selected_buttons_by_persona
      match '', to: 'channels#broadcast', :as => :broadcast_channel
    end
  end

  match '/:username', to: 'channels#index', :as => :home

  # 404ページ # develop環境で表示テストをするには、このunlessを外してください。
  # ApplicationController内のunlessも外してください。
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/channel.rb
class Channel
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :button_sets

  belongs_to :owner, :class_name => User.to_s, :inverse_of => :channels

  field :title, :type => String;
  field :description, :type => String;

  validates :title, :description, :presence => true

  def is_owned_by?(user)
    self.owner == user
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  layout 'layouts/settings'
  before_filter :login_user_only, :except => [:broadcast]

  def index
    @channels = login_user.channels.desc(:updated_at)
  end

  def broadcast
    render_404 unless @channel = current_user.channels.find(params[:channel_id])
    render :layout => 'layouts/broadcast'
  end

  def new
    case params[:type]
    when 'ustream'
      @channel = UstreamChannel.new
    when 'radiko'
      @channel = RadikoChannel.new
    else
      render_404
    end
  end

  def create
    params_ch =  params['ustream_channel'] || params['radiko_channel']

    case params_ch[:_type]
    when UstreamChannel.to_s
      @channel = UstreamChannel.new(params_ch)
    when RadikoChannel.to_s
      @channel = RadikoChannel.new(params_ch)
    else
      return render_404
    end
    @channel.owner = login_user

    @channel.button_sets.delete_all
    DefaultButtonSet.all.each do |default|
      set = ButtonSet.new
      set.name = default.name
      default.buttons.where(:tag.in => params[:ustream_channel][:button_tags]).each do |button|
        set.buttons << button
      end
      @channel.button_sets << set
    end

    if @channel.save
      redirect_to channels_path
    else
      render :new
    end
  end

  def edit
    return render_400 unless @channel = Channel.where(_id: params[:id]).first
  end

  def update
    @channel = login_user.channels.find(params[:id])
    @channel.button_sets.delete_all
    DefaultButtonSet.all.each do |default|
      set = ButtonSet.new
      set.name = default.name
      default.buttons.where(:tag.in => params[:ustream_channel][:button_tags]).each do |button|
        set.buttons << button
      end
      @channel.button_sets << set
    end

    if @channel.update_attributes(params[@channel.class.to_s.underscore])
      redirect_to edit_channel_path(@channel.id),
        flash: {notice: t('channels.update.saved',
                          path_to_broadcast_page: broadcast_channel_url(login_user.username, @channel.id, protocol: 'http'),
                         ).html_safe}
    else
      render :edit
    end
  end

  def destroy
    return render_400 unless @channel = Channel.where(_id: params[:id]).first
    @channel.destroy
    redirect_to channels_path
  end

  def get_buttons_by_persona
    channel = Channel.find(params['channel_id'])
    persona = Persona.find(params['persona_id'])
    buttons = Button.where(:button_se_id.in => ButtonSe.where(persona_id: persona.id).map(&:id)).order_by(:_id => :asc)
    render partial: 'components/buttons_for_edit_channel', locals: {buttons: buttons, channel: channel}
  end

  def get_selected_buttons_by_persona
    channel = Channel.find(params['channel_id'])
    persona = Persona.find(params['persona_id'])
    buttons = Button.where(:button_se_id.in => ButtonSe.where(persona_id: persona.id).map(&:id)).order_by(:_id => :asc)
    buttons = channel.button_sets.where(persona_id: persona.id).first.buttons
    render partial: 'components/buttons', locals: {buttons: buttons, channel: channel, on_change_selectbox: true}
  end

  def buttons
    @channel = Channel.where(_id: params[:id]).first || Channel.new
    @set = DefaultButtonSet.find(params[:set_id])
  end

  def selected_buttons
    @channel = Channel.where(_id: params[:id]).first || Channel.new
    @set = @channel.button_sets.find(params[:set_id])
  end

end

app/helpers/channels_helper.rb
module ChannelsHelper
  def owner?
     logged_in? and current_user == login_user
  end
end

app/views/channels/_form.html.slim
= form_for(@channel, url: @channel.new_record? ? channels_path : channel_path(@channel.id), html: {class: 'form-horizontal channel_form'}) do |f|
  - if @channel.errors.any?
    #error_explanation
      h2= t("mongoid.errors.models.channel.title", count: @channel.errors.count)
      ul
        - @channel.errors.full_messages.each do |msg|
          li= msg


  p.invalid_url= t('.invalid_url')
  / Ustreamの場合
  - if @channel.is_a? UstreamChannel
    .control-group
      label.control-label= t('.url')
      .controls
        = f.text_field(:url)
        span.btn.ac_ust_submit= t('.ac_ust')

  / Radikoの場合
  - if @channel.is_a? RadikoChannel
    .control-group
      label.control-label= t('.station_id')
      .controls
        = f.select(:station_id, Station.all.map{|s| [s.name, s.id]}, 'selected' => @channel.station_id)

  .control-group
    label.control-label= t('.title')
    .controls
      = f.text_field(:title)

  .control-group
    label.control-label= t('.description')
    .controls
      = f.text_area(:description)

  p.buttons_label= t('.buttons')
  = select_tag :button_set, options_for_select(DefaultButtonSet.asc(:created_at).map{|set| [set.name, set.id]}),
  onchange: "$.get('#{buttons_channel_path(@channel.id, '')}' + this.value)"
  .buttons-container
    = render partial: 'components/buttons_for_edit_channel', locals: {buttons: DefaultButtonSet.asc(:created_at).first.buttons, channel: @channel}

  = f.hidden_field(:_type)
  .control-group
    .controls
      = f.submit(@channel.new_record? ? t('.create') : t('.update'), class: 'btn')

app/views/channels/broadcast.html.slim
.main#broadcast_channel
  h1= @channel.title
  p= @channel.description
  p
    = t('.currently')
    span.num-listeners
    = t('.people_are_connecting')

  - if @channel.is_a?(UstreamChannel)
    .video-and-buttons.clearfix
      #video
        p= @channel.embed_tag.html_safe
      = select_tag :button_set,
        options_for_select(@channel.button_sets.map{|set| [set.name, set.id]}, selected: params[:set]),
        onchange: "location.href = '#{broadcast_channel_path(@channel.owner.username, @channel)}' + '?set=' + this.value";

      - set = params[:set].present? ? @channel.button_sets.where(_id: params[:set]).first : @channel.button_sets.first
      .buttons-container
        = render partial: 'components/buttons', locals: {buttons: set.buttons.asc(:tag)}

  - if @channel.is_owned_by?(login_user)
    #owner_actions
      p= t('.owner_actions')
      ul.actions
        li= link_to t('.edit'), edit_channel_path(@channel.id)

    #logs
      textarea

= content_for :bottom do
  javascript:
    window.ws_client = new RadiheyNode('#{RadiheyNode::URL}', JSON.parse('#{ Hash.new.tap {|hash| @channel.button_sets.map(&:buttons).flatten.map {|b| hash[b.id]= b.audio_file.audio} }.to_json.html_safe}'));
    window.ws_client.socket.on('connected', function(data){
      window.ws_client.socket.emit('join', {'room':'room#{@channel.id}'});
    });

app/views/channels/buttons.js.erb
var html = "<%= escape_javascript(render partial: 'components/buttons_for_edit_channel', locals: {buttons: @set.buttons, channel: @channel}) %>";
$(".buttons-container").html(html);

app/views/channels/edit.html.slim
.main#edit_channel
  h1= t('.title')
  = bootstrap_flash
  = render 'form'
  #owner_actions
    p= t('.owner_actions')
    ul.actions
      li= link_to t('.back'), channels_path
      li.separator |
      li= link_to t('.show_broadcast_page'), broadcast_channel_url(login_user.username, @channel.id, protocol: 'http'), target: '_blank'

app/views/channels/index.html.slim
.main#index_channel
  h1= t('.title', name: login_user.username)

  p
    = link_to t('.new'), new_channel_path(type: 'ustream'), class: 'btn new-btn'

  ul.channels
    - @channels.each do |channel|
      li.channel
        = image_tag 'default-channel-icon.png', class: 'icon'
        p= link_to channel.title, broadcast_channel_url(login_user.username, channel.id, protocol: 'http')
        p= channel.description
        ul.actions
          li= link_to t('.edit'), edit_channel_path(channel.id)
          li.separator |
          li= link_to t('.destroy'), channel_path(channel.id), :method => :delete, :confirm => t('.confirm')

app/views/channels/new.html.slim
.main#new_channel
  h1= t('.title')
  = render 'form'
  #owner_actions
    p= t('.owner_actions')
    ul.actions
      li= link_to t('.back'), channels_path

app/views/channels/selected_buttons.js.erb
var html = "<%= escape_javascript(render partial: 'components/buttons', locals: {buttons: @set.buttons}) %>";
$(".buttons-container").html(html);