config/routes.rb
# -*- coding: utf-8 -*-
RadiheyRails::Application.routes.draw do
  root to: 'top#show'

  match '/activate/:pre_register_token', to: 'users#activate', :as => :activate
  match 'activated', to: 'users#activated', :as => :activated
  match 'join', to: 'users#new', :as => :join
  match 'login', to: 'user_sessions#new', :as => :login
  match 'logout', to: 'user_sessions#destroy', :as => :logout

  #match 'account_settings', to: 'users#edit', :as => :account_settings

  resources :user_sessions

  resources :users do
    get :pre_registered
  end

  scope 'settings' do
    resources :button_images
    resources :default_button_sets do
      get :add_button, :on => :collection
      post :upload, :on => :collection
    end

    match 'account', to: 'users#edit', :as => :account_settings
    resources :buttons
    resources :button_ses do
      get 'list_all', :as => :list_all, :on => :collection
    end
    resources :channels do
      get "buttons/:set_id", action: "buttons", :on => :member, :as => :buttons
      get "selected_buttons/:set_id", action: "selected_buttons", :on => :member, :as => :selected_buttons
      get 'get_buttons/:persona_id', to: 'channels#get_buttons_by_persona', :as => :get_buttons_by_persona
    end
  end

  scope ":username" do
    scope ':channel_id' do
      match 'get_buttons/:persona_id', to: 'channels#get_selected_buttons_by_persona', :as => :get_selected_buttons_by_persona
      match '', to: 'channels#broadcast', :as => :broadcast_channel
    end
  end

  match '/:username', to: 'channels#index', :as => :home

  # 404ページ # develop環境で表示テストをするには、このunlessを外してください。
  # ApplicationController内のunlessも外してください。
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/button.rb
class Button
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  belongs_to :button_image
  belongs_to :audio_file

  field :tag,  type: Integer
  field :text, type: String

  validates :tag, :text, :audio_file_id, presence: true

end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  layout 'layouts/settings'
  before_filter :login_user_only

  def index
    @buttons = login_user.buttons.desc(:updated_at)
  end

  def show
    @button = login_user.buttons.find(params[:id])
  end

  def new
    @button = CustomButton.new
    @button_images = ButtonImage.all
  end

  def create
    @button = CustomButton.new(params[:custom_button])
    @button.owner = login_user
    if @button.save
      redirect_to buttons_path
    else
      @button_images = ButtonImage.all
      render :new
    end
  end

  def edit
    @button = login_user.buttons.find(params[:id])
    @button_images = ButtonImage.all
  end

  def update
    @button = login_user.buttons.find(params[:id])
    if @button.update_attributes(params[:custom_button])
      redirect_to edit_button_path(@button.id), flash: {notice: t('buttons.update.saved', path_to_index: buttons_path).html_safe}
    else
      @button_images = ButtonImage.all
      render :edit
    end
  end

  def destroy
    @button = login_user.buttons.find(params[:id])
    @button.destroy
    redirect_to buttons_path
  end
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/views/buttons/_form.html.slim
= form_for(@button,
  url: @button.new_record? ? buttons_path : button_path(@button.id),
  html: {class: 'form-horizontal'}) do |f|
  - if @button.errors.any?
    #error_explanation
      h2= t("mongoid.errors.models.button.title", count: @button.errors.count)
      ul
        - @button.errors.full_messages.each do |msg|
          li= msg

  .control-group
    label.control-label= t('.name')
    .controls
      = f.text_field(:name)

  .control-group
    label.control-label= t('.button_se')
    .controls
      = f.select(:button_se_id, ButtonSe.all.map{|s| [s.name, s.id]}, 'selected' => @button.button_se_id)
      = link_to list_all_button_ses_path(button_id: @button.id), class: 'reload_ses', remote: true do
        i.icon-refresh
        span.reload= t('.reload_ses')
      p= link_to t('.custom_button_se'), button_ses_path, target: '_blank'

  .control-group
    label.control-label= t('.button_label')
    .controls
      = f.text_field(:button_label)

  .control-group
    label.control-label= t('.button_image')
    .controls
      p.choose= t('.choose')

  .buttons-container
    - @button_images.each do |bi|
      .button_wrap(class='#{bi.name}')
        a.button_label= @button.button_label
        a(data-button_image_id='#{bi.id}' class="click_target #{' active' if @button.button_image_id == bi.id}")

  = f.hidden_field :button_image_id

  .control-group
    .controls
      = f.submit(value: @button.new_record? ? t('.create') : t('.update'), class: 'btn')

app/views/buttons/edit.html.slim
.main#edit_button
  h1= t('.title')
  = bootstrap_flash
  = render 'form'
  #owner_actions
    p= t('.owner_actions')
    ul.actions
      li= link_to t('.back'), buttons_path

app/views/buttons/index.html.slim
.main#index_button
  h1= t('.title')
  p
    = link_to t('.new'), new_button_path, class: 'btn new-btn'
  .buttons
    - @buttons.each do |button|
      .button_row
        .button_wrap
          = image_tag(button.button_image.filename)
          a.button_label= button.button_label
        .description
          p.button_name= button.name
          ul.actions
            li= link_to t('.edit'), edit_button_path(button.id)
            li.separator |
            li= link_to t('.destroy'), button_path(button.id), :method => :delete, :confirm => 'OK?'

          - if button.channels.count <= 0
            p= t('.not_used')
          - else
            p.used_by= t('.used_by')
            ul.used_by_channels
              - button.channels.each do |channel|
                li= link_to channel.title, broadcast_channel_url(channel.owner.username, channel.id, protocol: 'http'), target: '_blank'

app/views/buttons/new.html.slim
.main#new_button
  h1= t('.title')
  = render 'form'
  #owner_actions
    p= t('.owner_actions')
    ul.actions
      li= link_to t('.back'), buttons_path