config/routes.rb
# -*- coding: utf-8 -*-
RadiheyRails::Application.routes.draw do
  root to: 'top#show'

  match '/activate/:pre_register_token', to: 'users#activate', :as => :activate
  match 'activated', to: 'users#activated', :as => :activated
  match 'join', to: 'users#new', :as => :join
  match 'login', to: 'user_sessions#new', :as => :login
  match 'logout', to: 'user_sessions#destroy', :as => :logout

  #match 'account_settings', to: 'users#edit', :as => :account_settings

  resources :user_sessions

  resources :users do
    get :pre_registered
  end

  scope 'settings' do
    resources :button_images
    resources :default_button_sets do
      get :add_button, :on => :collection
      post :upload, :on => :collection
    end

    match 'account', to: 'users#edit', :as => :account_settings
    resources :buttons
    resources :button_ses do
      get 'list_all', :as => :list_all, :on => :collection
    end
    resources :channels do
      get "buttons/:set_id", action: "buttons", :on => :member, :as => :buttons
      get "selected_buttons/:set_id", action: "selected_buttons", :on => :member, :as => :selected_buttons
      get 'get_buttons/:persona_id', to: 'channels#get_buttons_by_persona', :as => :get_buttons_by_persona
    end
  end

  scope ":username" do
    scope ':channel_id' do
      match 'get_buttons/:persona_id', to: 'channels#get_selected_buttons_by_persona', :as => :get_selected_buttons_by_persona
      match '', to: 'channels#broadcast', :as => :broadcast_channel
    end
  end

  match '/:username', to: 'channels#index', :as => :home

  # 404ページ # develop環境で表示テストをするには、このunlessを外してください。
  # ApplicationController内のunlessも外してください。
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/default_button_set.rb
class DefaultButtonSet
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  has_and_belongs_to_many :buttons, inverse_of: nil

  validates :name, :presence => true

end

app/controllers/default_button_sets_controller.rb
class DefaultButtonSetsController < ApplicationController
  layout "settings"
  # GET /button_sets
  # GET /button_sets.json
  def index
    @button_sets = ButtonSet.all

    respond_to do |format|
      format.html
      format.json { render json: @button_sets }
    end
  end

  # GET /button_sets/1
  # GET /button_sets/1.json
  def show
    @button_set = ButtonSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @button_set }
    end
  end

  # GET /button_sets/new
  # GET /button_sets/new.json
  def new
    @button_set = params[:id] ? DefaultButtonSet.find(params[:id]).clone : DefaultButtonSet.new
    @button_set.name = nil

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @button_set }
    end
  end

  # GET /button_sets/1/edit
  def edit
    @button_set = DefaultButtonSet.find(params[:id])
  end

  # POST /button_sets
  # POST /button_sets.json
  def create
    @button_set = DefaultButtonSet.new(params[:default_button_set])
    params[:buttons].each do |btn|
      button = Button.create(btn)
      @button_set.buttons << button if button.valid?
    end

    respond_to do |format|
      if @button_set.save
        format.html { redirect_to default_button_sets_url, notice: 'Button set was successfully created.' }
        format.json { render json: @button_set, status: :created, location: @button_set }
      else
        format.html { render action: "new" }
        format.json { render json: @button_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /button_sets/1
  # PUT /button_sets/1.json
  def update
    @button_set = DefaultButtonSet.find(params[:id])
    params[:buttons].each do |btn|
      button = @button_set.buttons.where(:tag => btn[:tag]).first
      if button
        button.update_attributes btn
        button.destry unless button.valid?
      end
    end

    respond_to do |format|
      if @button_set.update_attributes(params[:default_button_set])
        format.html { redirect_to default_button_sets_url, notice: 'Button set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @button_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /button_sets/1
  # DELETE /button_sets/1.json
  def destroy
    @button_set = ButtonSet.find(params[:id])
    @button_set.destroy

    respond_to do |format|
      format.html { redirect_to button_sets_url }
      format.json { head :no_content }
    end
  end

  def upload
    audio = AudioFile.new(params["audio"])
    audio.save!
    render json: audio
  end

end

app/views/default_button_sets/_button.html.slim
tr.btn-row[data-index="#{(defined? index) ? index : 0}"]
  td.tag   = text_field_tag "buttons[][tag]", button.tag
  td.text  = text_field_tag "buttons[][text]", button.text
  td.audio
    - if button.audio_file
      span = button.audio_file.audio_file_name
      a.remove[href="#{upload_default_button_sets_path}"] Ｘ
    - else
      = file_field_tag "audio", "data-uploadpath" => upload_default_button_sets_path
  td.image = link_to "#", class: "choose-image" do
    - if button.button_image
      = image_tag button.button_image.image
    - else
      = image_tag "default-channel-icon.png"
  td.play
    a.btn.play[href="#{button.audio_file.try(:audio)}"]
      i.icon-bullhorn
  = hidden_field_tag "buttons[][audio_file_id]", button.audio_file_id, class: "audio-id"
  = hidden_field_tag "buttons[][button_image_id]", button.button_image_id, class: "image-id"

app/views/default_button_sets/_form.html.slim
= form_for(@button_set) do |f|
  span.title-suffix ‘ #{f.text_field("name")}
  span.title-prefix = t(".title_prefix")
  .buttons
    table.table.table-bordered
      tr
        th = t(".tag")
        th = t(".text")
        th = t(".audio")
        th = t(".image")
        th = t(".play")
      - @button_set.buttons.asc(:tag).each_with_index do |button, i|
        = render partial: "button", locals: { button: button, index: i }
      = render partial: "button", locals: { button: Button.new, index: @button_set.buttons.count }
    .control
      = link_to "ボタンを追加", add_button_default_button_sets_path, remote: true,  class: "add-button btn btn-primary"
  p.submit = f.submit "保存", class: "btn btn-success"

#image-dialog.modal.hide.fade
  .modal-header
    button.close[type="button" data-dismiss="modal" aria-hidden=true] ×
    h3 = t(".dialog_title")
  = render partial: "image_gallery"

app/views/default_button_sets/_image_gallery.html.slim
.modal-body
  .gallery
    - ButtonImage.all.each do |image|
      .wrap
        = image_tag image.image, "data-button_image" => image.id
        p = image.name
  .new
    = form_for ButtonImage.new, remote: true do |f|
      = text_field_tag "button_image[name]", nil, placeholder: "名前"
      label アイコン #{ file_field_tag "button_image[image]" }
      label クリックした時のアイコン #{ file_field_tag "button_image[image_clicked]" }
      = link_to "登録", "#", class: "submit btn btn-success", "data-uploadpath" => button_images_path

app/views/default_button_sets/add_button.js.erb
var html = "<%= escape_javascript(render partial: "button", locals: {button: Button.new, index: params[:index]}) %>";
var $html = $(html);
$html.data("index", $(".btn-row").size());
$("tbody").append($html);

app/views/default_button_sets/edit.html.slim
#edit_button_sets
  = render "form"
  = link_to 'Back', default_button_sets_path

app/views/default_button_sets/index.html.slim
h2 = t(".title")
table.table.table-hover
  - DefaultButtonSet.all.each do |button_set|
    tr
      td= link_to button_set.name, edit_default_button_set_path(button_set)
      td= link_to t(".copy"), new_default_button_set_path(id: button_set.id)
.new
  = link_to t(".new"), new_default_button_set_path

app/views/default_button_sets/new.html.slim
#new_button_sets
  = render "form"
  = link_to "Back", default_button_sets_path

app/views/default_button_sets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_button_set_path(@button_set) %> |
<%= link_to 'Back', button_sets_path %>