config/routes.rb
# -*- coding: utf-8 -*-
RadiheyRails::Application.routes.draw do
  root to: 'top#show'

  match '/activate/:pre_register_token', to: 'users#activate', :as => :activate
  match 'activated', to: 'users#activated', :as => :activated
  match 'join', to: 'users#new', :as => :join
  match 'login', to: 'user_sessions#new', :as => :login
  match 'logout', to: 'user_sessions#destroy', :as => :logout

  #match 'account_settings', to: 'users#edit', :as => :account_settings

  resources :user_sessions

  resources :users do
    get :pre_registered
  end

  scope 'settings' do
    resources :button_images
    resources :default_button_sets do
      get :add_button, :on => :collection
      post :upload, :on => :collection
    end

    match 'account', to: 'users#edit', :as => :account_settings
    resources :buttons
    resources :button_ses do
      get 'list_all', :as => :list_all, :on => :collection
    end
    resources :channels do
      get "buttons/:set_id", action: "buttons", :on => :member, :as => :buttons
      get "selected_buttons/:set_id", action: "selected_buttons", :on => :member, :as => :selected_buttons
      get 'get_buttons/:persona_id', to: 'channels#get_buttons_by_persona', :as => :get_buttons_by_persona
    end
  end

  scope ":username" do
    scope ':channel_id' do
      match 'get_buttons/:persona_id', to: 'channels#get_selected_buttons_by_persona', :as => :get_selected_buttons_by_persona
      match '', to: 'channels#broadcast', :as => :broadcast_channel
    end
  end

  match '/:username', to: 'channels#index', :as => :home

  # 404ページ # develop環境で表示テストをするには、このunlessを外してください。
  # ApplicationController内のunlessも外してください。
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/button_image.rb
class ButtonImage
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  has_many :buttons, :dependent => :destroy

  field :name, type: String
  has_mongoid_attached_file :image, {
    :path           => '/button_image/:attachment/:id/:filename',
    :storage        => :s3,
    :url            => ':s3_alias_url',
    :s3_host_alias  => S3::HOST,
    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')
  }
  has_mongoid_attached_file :image_clicked, {
    :path           => '/button_image/:attachment/:id/:filename',
    :storage        => :s3,
    :url            => ':s3_alias_url',
    :s3_host_alias  => S3::HOST,
    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')
  }

  validates :name, presence: true
  validates_attachment :image, :image_clicked, presence: true, size: {in: 0..1.megabytes}
  validates_attachment_content_type :image, :image_clicked, :content_type => /image\/*/
end

app/controllers/button_images_controller.rb
class ButtonImagesController < ApplicationController
  # GET /button_images
  # GET /button_images.json
  def index
    @button_images = ButtonImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @button_images }
    end
  end

  # GET /button_images/1
  # GET /button_images/1.json
  def show
    @button_image = ButtonImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @button_image }
    end
  end

  # GET /button_images/new
  # GET /button_images/new.json
  def new
    @button_image = ButtonImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @button_image }
    end
  end

  # GET /button_images/1/edit
  def edit
    @button_image = ButtonImage.find(params[:id])
  end

  # POST /button_images
  # POST /button_images.json
  def create
    @button_image = ButtonImage.new(params[:button_image])
    if @button_image.save
      #render "success"
      render partial: "default_button_sets/image_gallery"
    else
      render "fail"
    end
  end

  # PUT /button_images/1
  # PUT /button_images/1.json
  def update
    @button_image = ButtonImage.find(params[:id])

    respond_to do |format|
      if @button_image.update_attributes(params[:button_image])
        format.html { redirect_to @button_image, notice: 'Button image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @button_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /button_images/1
  # DELETE /button_images/1.json
  def destroy
    @button_image = ButtonImage.find(params[:id])
    @button_image.destroy

    respond_to do |format|
      format.html { redirect_to button_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/button_images_helper.rb
module ButtonImagesHelper
end

app/views/button_images/_form.html.erb
<%= form_for(@button_image) do |f| %>
  <% if @button_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@button_image.errors.count, "error") %> prohibited this button_image from being saved:</h2>

      <ul>
      <% @button_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/button_images/edit.html.erb
<h1>Editing button_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @button_image %> |
<%= link_to 'Back', button_images_path %>

app/views/button_images/index.html.erb
<h1>Listing button_images</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @button_images.each do |button_image| %>
  <tr>
    <td><%= link_to 'Show', button_image %></td>
    <td><%= link_to 'Edit', edit_button_image_path(button_image) %></td>
    <td><%= link_to 'Destroy', button_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Button image', new_button_image_path %>

app/views/button_images/new.html.erb
<h1>New button_image</h1>

<%= render 'form' %>

<%= link_to 'Back', button_images_path %>

app/views/button_images/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_button_image_path(@button_image) %> |
<%= link_to 'Back', button_images_path %>

app/views/button_images/success.js.erb
var html = "<%= escape_javascript(render partial: "default_button_sets/image_gallery") %>";
$("#image-dialog .gallery").replaceWith(html);